### ISSUE TITLE
Player shapeshifting.

### ISSUE THREAD

**Issue by DELTARUNEFAN1997** [ToCraft/SkinShifter#1]
### Describe your idea, include images if necessary

Ummm, not sure if this is already a feature (could not find) but If it isn’t then I would love it if you could shapeshift into other players. As I said if this is already a thing I apologize but I could not find a way to do it (if it is pls tell me how) imagine you walk up to someone who thinks your their friend and then backstab them mercilessly.

**Comment by ToCraft** [comment]
SkinShifter is finally available on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/skinshifter) and [Modrinth](https://modrinth.com/mod/skinshifter). I'll upload a ReMorphed update for compatibility soon, too.

**Comment by DELTARUNEFAN1997** [comment]
YEAH!!!
